plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

url: "https://ulkyome.github.io"

name: Ulkyome
description: test desc
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

copyright: false

#test: 
#    testtext: test2

#defaults:
#  -
#    scope:
#      path: "" # an empty string here means all files in the project
#      type: "posts"
#    values:
#      layout: "post"

#projects:
#  sort_by: pushed
#  # sort_by options:
#  #   - pushed
#  #   - stars
#  limit: 9
#  exclude:
#  - Gemfile
#  - Gemfile.lock
#  - LICENSE
#  - README.md
#  - CNAME
#    archived: false
#    forks: true
#    projects:
#    # - repo-name

social_media:
   behance: your_username
   dribbble: your_username
   facebook: your_username
   hackerrank: your_username
   instagram: your_username
   keybase: your_username
   linkedin: your_username
   mastodon: your_username
   medium: your_username
   stackoverflow: your_user_id
   telegram: your_username
   twitter: your_username
   unsplash: your_username
   vk: your_username
   youtube: your_username
   github_link: your_username
   email: ulkyome@gmail.com
   website: http://your_website_url
  
#topics:
#- name: CSS
#  web_url: https://github.com/topics/css
#  image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png
#
#- name: Web design
#
#- name: Sass
#  web_url: https://github.com/topics/sass
#  image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png